### ISSUE TITLE
Is there an alternative way to do the annotation without the GenBank file?

### ISSUE THREAD

**Issue by vappiah** [rpetit3/vcf-annotator#7]
Hello developer(s). I would like to use vcf-annotator on my plasmodium snp data. However there seems to be no genebank file available from the download site for the reference genome https://plasmodb.org/plasmo/app/downloads/release-49/Pfalciparum3D7/)

Is there an alternative way to do the annotation without the genebank file? Please advice

**Comment by rpetit3** [comment]
If its the same genome as this one [Plasmodium falciparum 3D7 (malaria parasite P. falciparum)](https://www.ncbi.nlm.nih.gov/assembly/GCF_000002765.5), then the GenBank file can be found here: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/765/GCF_000002765.5_GCA_000002765/GCF_000002765.5_GCA_000002765_genomic.gbff.gz

Be warned though, I've only tested vcf-annotator on prokaryotic genomes. I think it should work for you, but it might be slow.

**Comment by vappiah** [comment]
Thanks @rpetit3 .  I will try with the file

**Comment by rpetit3** [comment]
Great! Hope it works for you! If not please feel free to reopen this issue
